#mysql-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
